### ISSUE TITLE
ADD Noteした後に文字を入力してからlist選択した時の挙動がおかしい

### ISSUE THREAD

**Issue by kozzzz-07** [kozzzz-07/angular-note-app#1]
## 再現手順
1. 「+ADD Note」を複数回押下する
1. Listから適当なNoteを選択する
1. Noteに適当に文字を入力する
1. 別のlistを選択する
1. 選択されたListの情報がNoteに反映されるべきだが、そのままとなる

##  どうなってほしいか
Listの情報が反映されてほしい。

**Comment by kozzzz-07** [comment]
なんか挙動が怪しい時と安定している時がある

**Comment by mikuni392** [comment]
二番目を選択して編集してエンターキーなどを押さないで（編集を確定させないで）1番目を選択すると、二番目を選択した扱いになっているみたいです。

![ang](https://user-images.githubusercontent.com/51308564/95534770-a1390800-0a21-11eb-9170-91d8100db1a2.gif)

**Comment by komem3** [comment]
2番目を選択して、編集を確定させないで（エンターキーなどを押さないで）1番目を選択すると、2番目を選択したことになるみたいです。
おそらく、クリックのものを表示する前に保存処理が走っているのが原因かと思います。
![ang](https://user-images.githubusercontent.com/29977786/95535018-4f44b200-0a22-11eb-9159-0f4261f3fb6d.gif)
